from __future__ import annotations
import os
from ckanext.theming.lib import Theme


def make_theme(name: str = "nds-ui"):
    return Theme(name, os.path.dirname(__file__), icon_map=icon_map)


icon_map = {
    "bars": "menu",
    "battery-empty": "battery_0_bar",
    "battery-full": "battery_full",
    "battery-half": "battery_3_bar",
    "bell": "notifications",
    "bell-slash": "notifications_off",
    "calendar": "calendar_month",
    "chart-area": "area_chart",
    "chart-bar": "bar_chart",
    "chart-line": "show_chart",
    "chart-pie": "pie_chart",
    "check-circle": "check_circle",
    "chevron-down": "expand_more",
    "chevron-left": "chevron_left",
    "chevron-right": "chevron_right",
    "chevron-up": "expand_less",
    "clipboard": "content_paste",
    "clock": "schedule",
    "cloud-download": "cloud_download",
    "cloud-upload": "cloud_upload",
    "cog": "settings",
    "cogs": "build",
    "comments": "forum",
    "copy": "content_copy",
    "database": "storage",
    "ellipsis-h": "more_horiz",
    "ellipsis-v": "more_vert",
    "envelope": "mail",
    "envelope-open": "mark_email_read",
    "exclamation-triangle": "warning",
    "external-link": "open_in_new",
    "eye": "visibility",
    "eye-slash": "visibility_off",
    "file": "description",
    "file-csv": "table_view",
    "file-excel": "table_chart",
    "file-pdf": "picture_as_pdf",
    "filter": "filter_list",
    "folder-open": "folder_open",
    "globe": "public",
    "heart": "favorite",
    "info-circle": "info",
    "map-marker": "location_on",
    "minus": "remove",
    "play": "play_arrow",
    "plus": "add",
    "question-circle": "help",
    "signal": "signal_cellular_alt",
    "sliders": "tune",
    "sort-down": "arrow_downward",
    "sort-up": "arrow_upward",
    "star-half": "star_half",
    "table": "table_chart",
    "tag": "sell",
    "thumbs-down": "thumb_down",
    "thumbs-up": "thumb_up",
    "times": "close",
    "times-circle": "cancel",
    "trash": "delete",
    "unlock": "lock_open",
    "user": "person",
    "users": "group",
    "wrench": "build",
}
